# Generated by Django 5.1.4 on 2025-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
