# Generated by Django 5.1.4 on 2025-04-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
    ]
